### ISSUE TITLE
Code is outdated

### ISSUE THREAD

**Issue by theeosdev** [oraclize/eos-api#3]
The code is not compatible with EOSIO.CDT 1.4.0. Could you update it?

**Comment by riccardopersiani** [comment]
As far as we are concerned, the EOSIO.CDT has currently some open issues; so, we are waiting for a more stable version to release the `eos_api` updated for the new Contract Development Tool.

**Comment by theeosdev** [comment]
I think it's a bad decision. Deprecated unsupported code does not mean more stable. In addition, EOSIO.CDT version 1.4.1 has already been released. At the very least, you could host both versions and not force developers to use the legacy API.

**Comment by riccardopersiani** [comment]
@theeosdev, we just released a new version of the API compatible with the EOSIO.CDT and available in the Jungle 2.0 testnet.
